### ISSUE TITLE
HistogramBinning cannot be cloned

### ISSUE THREAD

**Issue by AnesBenmerzoug** [appliedAI-Initiative/kyle#2]
# Explanation

Instances of `HistogramBinning` cannot be cloned using sklearn's [`clone`](https://scikit-learn.org/stable/modules/generated/sklearn.base.clone.html) function.
This is relevant because it is used for example in the sklearn [`cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) function.

This error is due to the `HistogramBinning` estimator class not following [sklearn's requirements](https://scikit-learn.org/stable/developers/develop.html#instantiation) for an estimator, specifically this following one:

> In addition, every keyword argument accepted by __init__ should correspond to an attribute on the instance. Scikit-learn relies on this to find the relevant attributes to set on an estimator when doing model selection.

# How to reproduce

```python
from kyle.calibration.calibration_methods import HistogramBinning
from sklearn import clone

clone(HistogramBinning())
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anesbenmerzoug/workdir/repositories/transferlab/experiments-for-the-calibration-paper/venv/lib/python3.9/site-packages/sklearn/base.py", line 84, in clone
    new_object_params = estimator.get_params(deep=False)
  File "/home/anesbenmerzoug/workdir/repositories/transferlab/experiments-for-the-calibration-paper/venv/lib/python3.9/site-packages/sklearn/base.py", line 210, in get_params
    value = getattr(self, key)
AttributeError: 'HistogramBinning' object has no attribute 'bins'
```

# Suggested fix

To fix this we could simply change the [`HistogramBinning`](https://github.com/appliedAI-Initiative/kyle/blob/0d63c15984809bb4da313c90d1548b4bbf1f71ee/src/kyle/calibration/calibration_methods.py#L86-L88) class from:

```python
class HistogramBinning(NetcalBasedCalibration[bn.HistogramBinning]):
    def __init__(self, bins=20):
        super().__init__(bn.HistogramBinning(bins=bins))
```

to:

```python
class HistogramBinning(NetcalBasedCalibration[bn.HistogramBinning]):
    def __init__(self, bins=20):
        self.bins = bins
        super().__init__(bn.HistogramBinning(bins=bins))
```

**Comment by MischaPanch** [comment]
Fixed in #3
